/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import koneksi.konek;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Win 8
 */
public class SaranaKelas extends javax.swing.JFrame {

    /**
     * Creates new form AnalisisRuangKelas
     */
    public SaranaKelas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jComboBox3 = new javax.swing.JComboBox();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jComboBox7 = new javax.swing.JComboBox();
        jComboBox8 = new javax.swing.JComboBox();
        jComboBox9 = new javax.swing.JComboBox();
        jComboBox10 = new javax.swing.JComboBox();
        jComboBox11 = new javax.swing.JComboBox();
        jComboBox12 = new javax.swing.JComboBox();
        jComboBox13 = new javax.swing.JComboBox();
        jComboBox14 = new javax.swing.JComboBox();
        jComboBox15 = new javax.swing.JComboBox();
        jComboBox16 = new javax.swing.JComboBox();
        jComboBox17 = new javax.swing.JComboBox();
        jComboBox18 = new javax.swing.JComboBox();
        jComboBox19 = new javax.swing.JComboBox();
        jComboBox20 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(2147483647, 1174));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setText("Jumlah Stop Kontak :");

        jLabel2.setText("Kondisi Stop Kontak :");

        jLabel3.setText("Posisi Stop Kontak :");

        jLabel4.setText("Jumlah Kabel LCD :");

        jLabel5.setText("Kondisi Kabel LCD :");

        jLabel6.setText("Posisi Kabel LCD :");

        jLabel7.setText("Jumlah Lampu :");

        jLabel8.setText("Kondisi Lampu :");

        jLabel9.setText("Posisi Lampu :");

        jLabel10.setText("Jumlah Kipas Angin :");

        jLabel11.setText("Kondisi Kipas Angin :");

        jLabel12.setText("Posisi Kipas Angin   :");

        jLabel13.setText("Jumlah AC :");

        jLabel14.setText("Kondisi AC :");

        jLabel15.setText("Posisi AC :");

        jLabel16.setText("Pilih SSID :");

        jLabel17.setText("Konektifitas :");

        jLabel18.setText("Jumlah CCTV :");

        jLabel19.setText("Kondisi CCTV :");

        jLabel20.setText("Posisi CCTV   :");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel21.setText("Sarana Ruang Kelas");

        jLabel22.setText("Nama Ruang           :");

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 102));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "2", "4", "8" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Baik", "Kurang Baik", "Rusak" }));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Di pojok dan dekat dose", "Di tengah", "Di bawah" }));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "0", "1" }));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Berfungsi", "Kurang Baik", "Rusak" }));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Dekat Dosen", "Dekat Pintu", "Dekat Lampu" }));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "4", "10", "18" }));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Baik", "Kurang Baik", "Rusak" }));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Atap", "Bawah", "Samping" }));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "1", "2", "4" }));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Baik", "Kurang Baik", "Rusak" }));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Atap", "Bawah", "Samping" }));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "0", "1", "2" }));

        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Baik", "Kurang Baik", "Rusak" }));

        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Depan", "Samping", "Belakang" }));

        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "UMM Hotspot", "Riza Hotspot", "Gangga Hotspot", "Adi Hotspot" }));

        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Bisa Login", "Tidak Bisa Login" }));

        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "0", "1", "2" }));

        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Baik", "Kurang Baik", "Rusak" }));

        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Pilih-", "Depan", "Samping", "Belakang" }));

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Delete");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel7)
                                                    .addComponent(jLabel8)
                                                    .addComponent(jLabel9)
                                                    .addComponent(jLabel6)
                                                    .addComponent(jLabel5)
                                                    .addComponent(jLabel4))
                                                .addGap(35, 35, 35)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel1))
                                                .addGap(25, 25, 25)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addComponent(jLabel3))
                                        .addGap(46, 46, 46)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel17)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel10)
                                                    .addComponent(jLabel11)
                                                    .addComponent(jLabel12)
                                                    .addComponent(jLabel13)
                                                    .addComponent(jLabel14)
                                                    .addComponent(jLabel15))
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(17, 17, 17)
                                                        .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addGap(18, 18, 18)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                            .addComponent(jLabel16))
                                        .addGap(66, 66, 66)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel20)
                                                .addGap(48, 48, 48)
                                                .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel18)
                                                    .addComponent(jLabel19))
                                                .addGap(47, 47, 47)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)))
                                .addGap(98, 98, 98)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(401, 401, 401)
                .addComponent(jLabel21)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(jComboBox18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(jComboBox19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jComboBox20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton4)
                            .addComponent(jButton5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jComboBox14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jComboBox15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jComboBox16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jComboBox17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public SaranaKelas(JFrame frame) {
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        int x = (dim.width - frame.getSize().width) / 2;
        int y = (dim.height - frame.getSize().height) / 2;
        frame.setLocation(x, y);
    }
    public String namaruang;

    public String getNamaRuang() {
        return namaruang;
    }

    public void klik() {
        Dataruang1 fDR = new Dataruang1();
        fDR.SK = this;
        fDR.setVisible(true);
        jTextField1.setText(namaruang);

    }

    public void load() {
        Dataruang1 fDR = new Dataruang1();
        fDR.SK = this;
        jTextField1.setText(namaruang);

    }

    public JTextField getJTextField1() {
        return jTextField1;
    }

    public void klikInsert() {
        String namaruang = getJTextField1().getText();
        try {
            Statement statement = konek.GetConnection().createStatement();
            statement.executeUpdate("INSERT INTO sarana (namaruang,jmlstop,kondisistop,posisistop,jmllcd,kondisilcd,posisilcd,jmllampu,kondisilampu,posisilampu,jmlkipas,kondisikipas,posisikipas,jmlac,kondisiac,posisiac,pilihssid,konektifitas,jmlcctv,kondisicctv,posisicctv) VALUES ('" + namaruang + "','"
                    + jComboBox1.getSelectedItem() + "','" + jComboBox2.getSelectedItem() + "','" + jComboBox3.getSelectedItem() + "','" + jComboBox4.getSelectedItem() + "','" + jComboBox5.getSelectedItem() + "','" + jComboBox6.getSelectedItem() + "','" + jComboBox7.getSelectedItem() + "','" + jComboBox8.getSelectedItem() + "','" + jComboBox9.getSelectedItem() + "','" + jComboBox10.getSelectedItem() + "','" + jComboBox11.getSelectedItem() + "','" + jComboBox12.getSelectedItem() + "','" + jComboBox13.getSelectedItem() + "','" + jComboBox14.getSelectedItem() + "','" + jComboBox15.getSelectedItem() + "','" + jComboBox16.getSelectedItem() + "','" + jComboBox17.getSelectedItem() + "','" + jComboBox18.getSelectedItem() + "','" + jComboBox19.getSelectedItem() + "','" + jComboBox20.getSelectedItem() + "');");
            statement.close();
            JOptionPane.showMessageDialog(null, "Berhasil Memasukan Data");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal Memasukan data");
        }
    }

    public void klikReset() {
        jTextField1.setText("");
        jComboBox1.setSelectedItem("-pilih-");
        jComboBox2.setSelectedItem("-pilih-");
        jComboBox3.setSelectedItem("-pilih-");
        jComboBox4.setSelectedItem("-pilih-");
        jComboBox5.setSelectedItem("-pilih-");
        jComboBox6.setSelectedItem("-pilih-");
        jComboBox7.setSelectedItem("-pilih-");
        jComboBox8.setSelectedItem("-pilih-");
        jComboBox9.setSelectedItem("-pilih-");
        jComboBox10.setSelectedItem("-pilih-");
        jComboBox11.setSelectedItem("-pilih-");
        jComboBox12.setSelectedItem("-pilih-");
        jComboBox13.setSelectedItem("-pilih-");
        jComboBox14.setSelectedItem("-pilih-");
        jComboBox15.setSelectedItem("-pilih-");
        jComboBox16.setSelectedItem("-pilih-");
        jComboBox17.setSelectedItem("-pilih-");
        jComboBox18.setSelectedItem("-pilih-");
        jComboBox19.setSelectedItem("-pilih-");
        jComboBox20.setSelectedItem("-pilih-");
    }

    public void table() {
        Object header[] = {"Nama Ruang", "Jumlah Stop Kontak", "Kondisi Stop Kontak", "Posisi Stop Kontak", "Jumlah LCD", "Kondisi LCD", "Posisi LCD", "Jumlah Lampu", "Kondisi Lampu", "Posisi Lampu", "Jumlah Kipas", "Kondisi Kipas", "Posisi Kipas", "Jumlah AC", "Kondisi AC", "Posisi AC", "Pilih SSID", "Konektifitas", "Jumlah CCTV", "Kondisi CCTV", "Posisi CCTV"};
        DefaultTableModel data = new DefaultTableModel(null, header);
        jTable2.setModel(data);
        String sql = "select * from sarana";
        try {
            Statement st = konek.GetConnection().createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String kolom1 = rs.getString(1);
                String kolom2 = rs.getString(2);
                String kolom3 = rs.getString(3);
                String kolom4 = rs.getString(4);
                String kolom5 = rs.getString(5);
                String kolom6 = rs.getString(6);
                String kolom7 = rs.getString(7);
                String kolom8 = rs.getString(8);
                String kolom9 = rs.getString(9);
                String kolom10 = rs.getString(10);
                String kolom11 = rs.getString(11);
                String kolom12 = rs.getString(12);
                String kolom13 = rs.getString(13);
                String kolom14 = rs.getString(14);
                String kolom15 = rs.getString(15);
                String kolom16 = rs.getString(16);
                String kolom17 = rs.getString(17);
                String kolom18 = rs.getString(18);
                String kolom19 = rs.getString(19);
                String kolom20 = rs.getString(20);
                String kolom21 = rs.getString(21);

                String kolom[] = {kolom1, kolom2, kolom3, kolom4, kolom5, kolom6, kolom7, kolom8, kolom9, kolom10, kolom11, kolom12, kolom13, kolom14, kolom15, kolom16, kolom17, kolom18, kolom19, kolom20, kolom21};
                data.addRow(kolom);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "error :" + e.getMessage());
        }
    }

    public void hapus() {
        try {
            Statement statement = konek.GetConnection().createStatement();
            String sql = "delete from sarana where namaruang='" + jTextField1.getText() + "'";
            statement.executeUpdate(sql);
            statement.close();

            table();
            klikReset();
            JOptionPane.showMessageDialog(null, "Data berhasil di hapus");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Proses hapus gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }

    public void edit() {
        try {

            Statement statement = konek.GetConnection().createStatement();
            String sql = "update sarana set jmlstop='" + jComboBox1.getSelectedItem() + "',"
                    + " kondisistop='" + jComboBox2.getSelectedItem() + "',"
                    + " posisistop='" + jComboBox3.getSelectedItem() + "',"
                    + " jmllcd='" + jComboBox4.getSelectedItem() + "',"
                    + " kondisilcd='" + jComboBox5.getSelectedItem() + "',"
                    + " posisilcd='" + jComboBox6.getSelectedItem() + "',"
                    + " jmllampu='" + jComboBox7.getSelectedItem() + "',"
                    + " kondisilampu='" + jComboBox8.getSelectedItem() + "',"
                    + " posisilampu='" + jComboBox9.getSelectedItem() + "',"
                    + " jmlkipas='" + jComboBox10.getSelectedItem() + "',"
                    + " kondisikipas='" + jComboBox11.getSelectedItem() + "',"
                    + " posisikipas='" + jComboBox12.getSelectedItem() + "',"
                    + " jmlac='" + jComboBox13.getSelectedItem() + "',"
                    + " kondisiac='" + jComboBox14.getSelectedItem() + "',"
                    + " posisiac='" + jComboBox15.getSelectedItem() + "',"
                    + " pilihssid='" + jComboBox16.getSelectedItem() + "',"
                    + " konektifitas='" + jComboBox17.getSelectedItem() + "',"
                    + " jmlcctv='" + jComboBox18.getSelectedItem() + "',"
                    + " kondisicctv='" + jComboBox19.getSelectedItem() + "',"
                    + " posisicctv='" + jComboBox20.getSelectedItem() + "'"
                    + "where namaruang='" + jTextField1.getText() + "'";
            statement.executeUpdate(sql);
            statement.close();

            table();
            klikReset();
            JOptionPane.showMessageDialog(null, "Data berhasil di rubah");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Proses update gagal/koneksi gagal..");
            System.out.println(e.getMessage());
        }
    }
    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        frame.setSize(400, 400);
        new SaranaKelas(this);
        load();
        table();
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        klik();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        klikInsert();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        try {
            int row = jTable2.rowAtPoint(evt.getPoint());

            String namaruang = jTable2.getValueAt(row, 0).toString();
            String jmlstop = jTable2.getValueAt(row, 1).toString();
            String kondisistop = jTable2.getValueAt(row, 2).toString();
            String posisistop = jTable2.getValueAt(row, 3).toString();
            String jmllcd = jTable2.getValueAt(row, 4).toString();
            String kondisilcd = jTable2.getValueAt(row, 5).toString();
            String posisilcd = jTable2.getValueAt(row, 6).toString();
            String jmllampu = jTable2.getValueAt(row, 7).toString();
            String kondisilampu = jTable2.getValueAt(row, 8).toString();
            String posisilampu = jTable2.getValueAt(row, 9).toString();
            String jmlkipas = jTable2.getValueAt(row, 10).toString();
            String kondisikipas = jTable2.getValueAt(row, 11).toString();
            String posisikipas = jTable2.getValueAt(row, 12).toString();
            String jmlac = jTable2.getValueAt(row, 13).toString();
            String kondisiac = jTable2.getValueAt(row, 14).toString();
            String posisiac = jTable2.getValueAt(row, 15).toString();
            String pilihssid = jTable2.getValueAt(row, 16).toString();
            String konektifitas = jTable2.getValueAt(row, 17).toString();
            String jmlcctv = jTable2.getValueAt(row, 18).toString();
            String kondisicctv = jTable2.getValueAt(row, 19).toString();
            String posisicctv = jTable2.getValueAt(row, 20).toString();

            jTextField1.setText(String.valueOf(namaruang));
            jComboBox1.setSelectedItem(String.valueOf(jmlstop));
            jComboBox2.setSelectedItem(String.valueOf(kondisistop));
            jComboBox3.setSelectedItem(String.valueOf(posisistop));
            jComboBox4.setSelectedItem(String.valueOf(jmllcd));
            jComboBox5.setSelectedItem(String.valueOf(kondisilcd));
            jComboBox6.setSelectedItem(String.valueOf(posisilcd));
            jComboBox7.setSelectedItem(String.valueOf(jmllampu));
            jComboBox8.setSelectedItem(String.valueOf(kondisilampu));
            jComboBox9.setSelectedItem(String.valueOf(posisilampu));
            jComboBox10.setSelectedItem(String.valueOf(jmlkipas));
            jComboBox11.setSelectedItem(String.valueOf(kondisikipas));
            jComboBox12.setSelectedItem(String.valueOf(posisikipas));
            jComboBox13.setSelectedItem(String.valueOf(jmlac));
            jComboBox14.setSelectedItem(String.valueOf(kondisiac));
            jComboBox15.setSelectedItem(String.valueOf(posisiac));
            jComboBox16.setSelectedItem(String.valueOf(pilihssid));
            jComboBox17.setSelectedItem(String.valueOf(konektifitas));
            jComboBox18.setSelectedItem(String.valueOf(jmlcctv));
            jComboBox19.setSelectedItem(String.valueOf(kondisicctv));
            jComboBox20.setSelectedItem(String.valueOf(posisicctv));
            jButton1.setVisible(false);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(true);
            jButton5.setVisible(true);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        edit();
        klikReset();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        hapus();
        klikReset();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        klikReset();
            jButton1.setVisible(true);
            jButton2.setVisible(true);
            jButton3.setVisible(true);
            jButton4.setVisible(false);
            jButton5.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaranaKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaranaKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaranaKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaranaKelas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaranaKelas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox13;
    private javax.swing.JComboBox jComboBox14;
    private javax.swing.JComboBox jComboBox15;
    private javax.swing.JComboBox jComboBox16;
    private javax.swing.JComboBox jComboBox17;
    private javax.swing.JComboBox jComboBox18;
    private javax.swing.JComboBox jComboBox19;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox20;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
